version: "3"
services:
  db:
    build: ../pg-vec-geo
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - ./pg-data/pg-data:/var/lib/postgresql/data 
  # nominatim:
  #   image: mediagis/nominatim:4.4
  #   restart: always
  #   environment:
  #     - PBF_URL=https://download.geofabrik.de/europe-latest.osm.pbf
  #     - IMPORT_STYLE=admin
  #   ports:
  #     - "8022:8080"
  #   volumes:
  #     - ./nominatim-data/pg:/var/lib/postgresql/14/main
  #     - ./nominatim-data/flatnode:/nominatim/flatnode
  pgadmin:
    image: dpage/pgadmin4:8.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@va-tu.at
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "10002:80"
    volumes:       
      - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./pgpass:/pgpass # passwords for the connections in this file
      # - ./pg-admin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  pg-data:
    external: false
      